Feature: Actor images on movies page
yourdrug/dbmovies pull request #1
Opened 2024-01-08 12:55 UTC by yourdrug

**Description:**
This pull request introduces a new feature that displays images of actors in the context of a movie. The Profession model now includes an image field, representing how the actor appears in a specific film. This enhancement is aimed at providing users with a visual representation of the actors in the movie.

**Implementation Details:**

Added an image field to the Profession model.
Utilized the upload_to function to define a dynamic path for storing actor images based on the associated movie and person names.
Modified the frontend to show actor images upon hovering over their names in the movie details view.

**Example Usage:**

Navigate to a movie details page.
Hover over the name of an actor in the list.
An image of the actor as they appear in the movie will be displayed.
This enhancement contributes to a richer and more engaging movie viewing experience by providing visual context about the actors involved in a film.

**Note:**

The images are sourced from the Profession model and are displayed dynamically upon user interaction.
This feature enhances the overall user interface and provides valuable insights into the appearance of actors in a specific movie.
![Снимок экрана от 2024-01-08 15-54-13](https://github.com/yourdrug/dbmovies/assets/106438523/bf75b3bd-4399-40a9-9e53-5d8d3992686d)
![Снимок экрана от 2024-01-08 15-54-50](https://github.com/yourdrug/dbmovies/assets/106438523/d31b72c0-5199-4be9-a705-af55d88be219)

2024-01-08 13:42 UTC, KoreshKrasa requested changes

2024-01-08 13:42 UTC, KoreshKrasa commented on ui/src/components/movie-by-id/movie-by-id.component.jsx
> +    const [hoveredActor, setHoveredActor] = useState(null);
Use plain css for this functionality

2024-01-08 15:58 UTC, KoreshKrasa commented
Don't use  foo.component.jsx or foo.styles.css. Just Foo.jsx and foo.css

2024-01-08 16:26 UTC, yourdrug commented
@KoreshKrasa, done it

2024-01-09 11:54 UTC, KoreshKrasa approved these changes

2024-01-09 12:23 UTC, merged